// <auto-generated />
using CarRental_WebAPI_Xamarin_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRental_WebAPI_Xamarin_Backend.Migrations
{
    [DbContext(typeof(CarRental_Database))]
    partial class CarRental_DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRental_WebAPI_Xamarin_Backend.Models.Car_Details", b =>
                {
                    b.Property<string>("RegNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Car_Maker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Car_Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Car_Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegNumber");

                    b.ToTable("Car_Details");
                });

            modelBuilder.Entity("CarRental_WebAPI_Xamarin_Backend.Models.Customer", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cust_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserName");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
